/// Flutter icons GmailPocIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GmailPocIcons
///      fonts:
///       - asset: fonts/GmailPocIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GmailPocIcons {
  GmailPocIcons._();

  static const _kFontFam = 'GmailPocIcons';
  static const _kFontPkg = null;

  static const IconData action_archive = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData action_delete = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData action_download_all = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData action_forward_button = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData action_forward = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData action_print = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData action_reply_all_button = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData action_reply_button = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData action_reply = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData action_unread = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach_download = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach_pdf = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compose_mail = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dd_listing = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dd_navigation = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData draft_navigation = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ellipse_6_copy_4 = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ellipse_6_copy_5 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData import_navigation = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox_navigation = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData label_navigation_hover = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData label_navigation = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData label_new_navigation = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_navigation = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_icon = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData selected_star_listing = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sent_navigation = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snoozed_navigation = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_listing = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_navigation = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector_smart_object2_copy = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData label_more_navigation = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
